# See example script at https://github.com/JuliaLang/Example.jl
language: julia

os:
  - linux
  - osx

julia:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - nightly

notifications:
  email: false

codecov: false

coveralls: true

jobs:
  allow_failures:
    - julia: nightly
# include:
#   - stage: "Documentation"
#     julia: 1.6
#     os: linux
#     script:
#       - export JULIA_LOAD_PATH='docs/:.:'
#       - julia -e 'using Pkg;
#                   Pkg.instantiate();
#                   Pkg.add("Documenter")'
#       - julia docs/make.jl
#     after_success: skip
